source :rubygems

gem 'capybara'
gem 'capybara-webkit'
gem 'compass'
gem 'compass-susy-plugin'
gem 'compass-validator'
gem 'cucumber'
gem 'geo_magic'
gem 'growl'
gem 'guard'
gem 'guard-compass'
gem 'guard-livereload'
gem 'guard-shell'
gem 'jasmine'
gem 'livereload'
gem 'rake'
gem 'rspec-expectations'
gem 'sass'
gem 'selenium-webdriver'
gem 'zayin'

