<?php
$logger->info('The wkt is: ' . $wkt);
//$logger->info("Item tags: " . print_r($item->getTags(),true));
$tags = array();
foreach ($item->getTags() as $tag) {
	array_push($tags, $tag->name);
}
/* the following query should restrict our returned items to Historical maps that
 share all of our items tags. we may need to change this to sharing any of our
 items tags. */
/*
$query = array("type" => $NEATLINEMAPS_ITEMTYPE, 'tags' => implode(',',$tags));
$logger->info("The background map query is:" . print_r($query,true));
$backgroundMaps = get_items($query);
//$logger->info("The background maps are: " . print_r($backgroundMaps,true));
$backgroundLayers = array();
foreach ( $backgroundMaps as $map)
{
	//$map = get_item_by_id($mapid,'Item');
	$logger->info("Now processing an item with id: " . $map->id);
	$layertitle = 'A map with no title';
	try {
		$layertitle = item( 'Dublin Core', 'Title', array('delimiter' => ',', 'snippet' => 20, 'all' => true),$map);
	}
	catch (Omeka_Record_Exception $e) {
		$logger->err($e);
	}
	$serviceaddy = getServiceAddy($map);
	$layername = getLayerName($map);
	$backgroundLayers[$layertitle] = array('layername' => $layername, 'serviceaddy' => $serviceaddy);
}
*/
# temporary fix for ignoring background maps
$backgroundLayers = array();
?>

<!--link
	rel="stylesheet"
	href="<?php # echo css('ui-lightness/jquery-ui-1.7.2.custom'); ?>" /> -->
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/overcast/jquery-ui.css" type="text/css" />
<link rel="stylesheet"
	href="http://dev.openlayers.org/releases/OpenLayers-2.8/theme/default/style.css"
	type="text/css" />
<link rel="stylesheet" href="<?php echo css('edit'); ?>" />

<script type="text/javascript"
	src="http://openlayers.org/api/OpenLayers.js">Ê</script>

	
<?php
echo js('jquery-1.3.2.min');
echo js('jquery-ui-1.7.2.custom.min');
echo js("features/edit/edit"); 
?>

<script
	type="text/javascript" defer="defer">
	//<![CDATA[
	jQuery.noConflict();
	inputNameStem = "<?php echo $inputNameStem; ?>";	
	layers = new Array();
	<?php 
		foreach ($backgroundLayers as $layername => $layervalues) {
 		   ?> 
 		   layers.push( { "title":"<?php echo $layername ?>", 
  				   			"address":"<?php echo $layervalues["serviceaddy"] ?>",
  		 				   	"layername":"<?php echo $layervalues["layername"] ?>" } ) ;
 		   <?php 
		}
	?>

	jQuery(document).ready(function() {
		jQuery("#coveragemap").dialog({
			autoOpen: false,
			modal:true,
			width: 800,
			height: 600,
			closeOnEscape: true
			})
		jQuery('#mapbutton').click(function() {
			jQuery("#coveragemap").dialog('open');
		});

		edit();

		});			
	//]]> 	
</script> 

<div id="coveragetext"><?php echo $textarea; ?></div>
<div id="mapbutton" class="submit submit-medium">Edit Coverage</div>
<div id='coveragemap' title="Coverage" class="">
	<div id="map" style='height: 400px;width: 700px;border: 1px solid #ccc;float: right;'></div>
	<div id="mappanel" class="olControlEditingToolbar"></div>
</div>
<div id="mappreview"></div>
<div id="addlayerdialog">
<?php

$items = get_items(array('type' => neatlinefeatures_getMapItemType() ), 200);
$itemnames = array();
$itemids = array();
foreach ($items as $item) {
	array_push($itemnames,item("Dublin Core", "Title", array(), $item));
	array_push($itemids,$item->id);
}
$options = array_combine($itemids,$itemnames);
echo $this->formSelect("layerselect", reset($options), array('class'=>'select'), $options);
?>
</div>

