<!--link
	rel="stylesheet"
	href="<?php # echo css('ui-lightness/jquery-ui-1.7.2.custom'); ?>" /> -->
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/overcast/jquery-ui.css" type="text/css" />
<link rel="stylesheet" href="<?php echo css('edit'); ?>" />

<script type="text/javascript"
	src="http://openlayers.org/api/OpenLayers.js">Ê</script>
<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js">Ê</script>
<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7/jquery-ui.min.js">Ê</script>
<?php
echo js('proj4js/proj4js-compressed');
echo js("widgets/edit/edit"); 
?>

<script type="text/javascript">
	//<![CDATA[
	jQuery.noConflict();
	inputNameStem = "<?php echo $inputNameStem; ?>";	

	jQuery(document).ready(function() {
		jQuery("#coveragemap").dialog({
			autoOpen: false,
			modal:true,
			width: 800,
			height: 600,
			closeOnEscape: true
			})
		jQuery('#mapbutton').click(function() {
			jQuery("#coveragemap").dialog('open');
		});

		Omeka.NeatlineFeatures.edit();

		});			
	//]]> 	
</script> 

<div id="coveragetext"><?php echo $textarea; ?></div>
<div id="mapbutton" class="submit submit-medium">Edit Coverage</div>
<div id='coveragemap' title="Coverage" class="">
	<div id="map" style='height: 400px;width: 700px;border: 1px solid #ccc;float: right;'></div>
	<div id="mappanel" class="olControlEditingToolbar"></div>
</div>

<div id="addlayerdialog">
<div id="mappreview"></div>
<?php

$items = get_items(array('type' => neatlinefeatures_getMapItemType() ), 200);
$itemnames = array();
$itemids = array();
foreach ($items as $item) {
	array_push($itemnames,item("Dublin Core", "Title", array(), $item));
	array_push($itemids,$item->id);
}
$options = array_combine($itemids,$itemnames);
echo $this->formSelect("layerselect", reset($options), array('class'=>'select'), $options);
?>
</div>

